---
- name: "Move interface to zone"
  tags: nat.firewall.zone
  ansible.builtin.lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ item['interface'] }}"
    regexp: "^ZONE=.*"
    line: "ZONE={{ item['zone'] }}"
  loop: "{{ nat_interfaces }}"
  loop_control:
    label: "{{ item['interface'] }} zone={{ item['zone'] }}"
  notify: "Reload and Restart Network Manager"

- name: "Allow masquerade on public interface"
  tags: nat.firewall.masquerade
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    state: enabled
    zone: public
    masquerade: "yes"
