---
- name: "Configure firewall"
  tags:
    - nat
    - nat.firewall
  import_tasks: firewall.yaml

- name: "Configure ip forwarding"
  tags:
    - nat
    - nat.routing
  import_tasks: routing.yaml
