---
- name: "Allow ip forwarding"
  tags: nat.routing.forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'

- name: "Disable default routing for non-public interfaces"
  tags: nat.routing.internal
  ansible.builtin.lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ item['interface'] }}"
    regexp: "^DEFROUTE=.*"
    line: "DEFROUTE=no"
  loop: "{{ nat_interfaces | rejectattr('zone','eq','public') }}"
  loop_control:
    label: "{{ item['interface'] }}"
  notify: "Reload and Restart Network Manager"
